name: dripp
description: "Decentralized, Peer to Peer, privacy focussed Social Network"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_sdk: ^3.0.1
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.6
  rxdart: ^0.28.0
  uuid: ^4.5.1
  video_player: ^2.9.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  # Add assets section to properly include your icon files
  assets:
  - assets/
  - assets/icons/
  - assets/icon.png
  - assets/images/
  - assets/images/image.png
  - assets/images/image-1.png

  fonts:
  - family: SpaceGrotesk
    fonts:
    - asset: assets/fonts/SpaceGrotesk-Regular.ttf
    - asset: assets/fonts/SpaceGrotesk-Bold.ttf
      weight: 700
  - family: Inter
    fonts:
    - asset: assets/fonts/Inter-Regular.ttf
    - asset: assets/fonts/Inter-Bold.ttf
      weight: 700
