name: dripp
description: "Decentralized, Peer to Peer, privacy focussed Social Network"
publish_to: 'none'
uses-material-design: true
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0
  rxdart: ^0.28.0
  image_picker: ^1.1.2
  video_player: ^2.9.2
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  macos: true
  windows: true
  linux: true
  web: true
  image_path: "assets/icon.png"

flutter:
  fonts:
  - family: MaterialIcons
    fonts:
    - asset: assets/fonts/MaterialIcons-Regular.ttf
  - family: SpaceGrotesk
    fonts:
    - asset: assets/fonts/SpaceGrotesk-Regular.ttf
    - asset: assets/fonts/SpaceGrotesk-Bold.ttf
      weight: 700
  - family: Inter
    fonts:
    - asset: assets/fonts/Inter-Regular.ttf
    - asset: assets/fonts/Inter-Bold.ttf
      weight: 700
